### ISSUE TITLE
Update go dependency 

### ISSUE THREAD

**Issue by marijana-rukavina** [bahmutov/cy-grep#24]
**Describe the bug**

Node.js version: 16.18.0
OS & version: Windows 10

When I run the npm install I get some moderate severity vulnerabilities. When I do `npm audit` I get the following;

![image](https://user-images.githubusercontent.com/84860380/215731483-d58c4c16-9e50-4754-92ab-f8f6deb28509.png)

**Actual behavior**
Vulnerabilities message is shown

**Expected behavior**
I want to resolve these vulnerabilities caused by got package

**Comment by bahmutov** [comment]
fixed in https://github.com/bahmutov/cy-grep/commit/64d6ed0da7a112b321bb0c990d61a021f9a138af
