### ISSUE TITLE
Getting TS2769: No overload matches this call. with typescript when using tags on "It" statements

### ISSUE THREAD

**Issue by nerrante** [bahmutov/cy-grep#60]
Hi Gleb!  I'm sure I'm missing something obvious but I triple checked my set up and it follows what you have in the instructions.  I can use tags in "Describe" and "Context" just fine with no problems, but not in "It" - it gives me the typescript error "TS2769: No overload matches this call."  Any thoughts??

**Comment by bahmutov** [comment]
Can you provide a reproducible example?Sent from my iPhoneOn May 12, 2023, at 16:40, nerrante ***@***.***> wrote:﻿
Hi Gleb!  I'm sure I'm missing something obvious but I triple checked my set up and it follows what you have in the instructions.  I can use tags in "Describe" and "Context" just fine with no problems, but not in "It" - it gives me the typescript error "TS2769: No overload matches this call."  Any thoughts??

**Comment by nerrante** [comment]
Yes, sorry! That's what I get for multitasking...I was updating my comment when you replied! here's my code (with some stuff redacted, if I need to put it back in let me know).

here's the error:
![image](https://github.com/bahmutov/cy-grep/assets/32847378/842fedf2-cb2c-47e6-be9e-ed3e1c94d1b9)


cypress.config.ts
```javascript
import { defineConfig } from 'cypress'
// https://github.com/jprichardson/node-fs-extra
import { removeSync, rename } from 'fs-extra'
import { readdirSync } from 'fs'
// https://github.com/cthackers/adm-zip
import AdmZip from 'adm-zip'
import XLSX from 'xlsx'


module.exports = defineConfig({
  e2e: {
    chromeWebSecurity: false,
    defaultCommandTimeout: 20000,
    experimentalInteractiveRunEvents: true,
    reporter: 'cypress-multi-reporters',
    requestTimeout: 20000,
    responseTimeout: 30000,
    retries: {
      runMode: 1,
    },
    trashAssetsBeforeRuns: false,
    video: false,
    watchForFileChanges: false,
    baseUrl: 'redactedbaseurl',
    reporterOptions: {
      reporterEnabled: 'spec, mocha-junit-reporter',
    },
    specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
    numTestsKeptInMemory: 0,
    env: {
      authCookieName: 'redactedcookie'
      CYPRESS_API_URL: 'http://localhost:1234/',
      grepFilterSpecs: true,
      grepOmitFiltered: true,
      showLogs: true,
      numTestsKeptInMemory: 0,
    },
    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser, launchOptions) => {
        if (browser.name === 'chrome' && browser.isHeadless) {
          //will not work when ssh into testrunner without these settings
          launchOptions.args.push('--disable-gpu');
          launchOptions.args.push('--disable-gpu-sandbox');
          launchOptions.args.push("--incognito");
          //https://blog.hao.dev/fixing-cypress-errors-part-1-chromium-out-of-memory-crashes
          launchOptions.args.push('--disable-dev-shm-usage');
        }
        return launchOptions
      });
      on('task', {
            //bunch of stuff here
      })
      require('@bahmutov/cy-grep/src/plugin')(config);
      // https://github.com/bahmutov/cypress-failed-log
      require('cypress-failed-log/on')(on);
      return config;
    }
  }
})
``` 
support/e2e.js
```javascript
import './commands'

// https://github.com/dmtrKovalenko/cypress-real-events;
import 'cypress-real-events/support'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import registerCypressGrep from '@bahmutov/cy-grep'
registerCypressGrep()

// https://github.com/filiphric/cypress-plugin-api
import 'cypress-plugin-api'

// eslint-disable-next-line mocha/no-top-level-hooks
beforeEach(function () {
    Cypress.env('transactionGUIDS', [])
})

Cypress.on('uncaught:exception', (err) => {
 //some code here
})

require('cypress-failed-log')

Cypress.Keyboard.defaults({
  keystrokeDelay: 20,
})
``` 
tsconfig.json
```javascript
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "es5",
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "types": [
      "cypress",
      "@testing-library/cypress",
      "@bahmutov/cy-grep",
      "cypress-real-events",
      "diff",
      "fs-extra",
      "adm-zip"
    ],
    "strict": true,
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowJs": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "isolatedModules": false,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "**/*.ts",
    "**/*.js"
  ],
}
``` 

example test file that will give error
```javascript
describe('Test test', { tags: ['@regression'] }, function () {
  context('Testing code', { tags: ['@this'] }, function () {
    it(`Does something good`, { tags: ['@that'] },function () {
      cy.contains('button', 'Start').click()
    })
  })
})

```

**Comment by bahmutov** [comment]
Great that you have pasted the code but can you make it into a public repo that I can clone, npm install and then see the problem right away?Sent from my iPhoneOn May 12, 2023, at 16:58, nerrante ***@***.***> wrote:﻿
Yes, sorry! That's what I get for multitasking...I was updating my comment when you replied! here's my code (with some stuff redacted, if I need to put it back in let me know).
here's the error:

cypress.config.ts
import { defineConfig } from 'cypress'
// https://github.com/jprichardson/node-fs-extra
import { removeSync, rename } from 'fs-extra'
import { readdirSync } from 'fs'
// https://github.com/cthackers/adm-zip
import AdmZip from 'adm-zip'
import XLSX from 'xlsx'


module.exports = defineConfig({
  e2e: {
    chromeWebSecurity: false,
    defaultCommandTimeout: 20000,
    experimentalInteractiveRunEvents: true,
    reporter: 'cypress-multi-reporters',
    requestTimeout: 20000,
    responseTimeout: 30000,
    retries: {
      runMode: 1,
    },
    trashAssetsBeforeRuns: false,
    video: false,
    watchForFileChanges: false,
    baseUrl: 'redactedbaseurl',
    reporterOptions: {
      reporterEnabled: 'spec, mocha-junit-reporter',
    },
    specPattern: 'cypress/e2e/**/*.{js,jsx,ts,tsx}',
    numTestsKeptInMemory: 0,
    env: {
      authCookieName: 'redactedcookie'
      CYPRESS_API_URL: 'http://localhost:1234/',
      grepFilterSpecs: true,
      grepOmitFiltered: true,
      showLogs: true,
      numTestsKeptInMemory: 0,
    },
    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser, launchOptions) => {
        if (browser.name === 'chrome' && browser.isHeadless) {
          //will not work when ssh into testrunner without these settings
          launchOptions.args.push('--disable-gpu');
          launchOptions.args.push('--disable-gpu-sandbox');
          launchOptions.args.push("--incognito");
          //https://blog.hao.dev/fixing-cypress-errors-part-1-chromium-out-of-memory-crashes
          launchOptions.args.push('--disable-dev-shm-usage');
        }
        return launchOptions
      });
      on('task', {
            //bunch of stuff here
      })
      ***@***.***/cy-grep/src/plugin')(config);
      // https://github.com/bahmutov/cypress-failed-log
      require('cypress-failed-log/on')(on);
      return config;
    }
  }
})
support/e2e.js
import './commands'

// https://github.com/dmtrKovalenko/cypress-real-events;
import 'cypress-real-events/support'

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import registerCypressGrep from ***@***.***/cy-grep'
registerCypressGrep()

// https://github.com/filiphric/cypress-plugin-api
import 'cypress-plugin-api'

// eslint-disable-next-line mocha/no-top-level-hooks
beforeEach(function () {
    Cypress.env('transactionGUIDS', [])
})

Cypress.on('uncaught:exception', (err) => {
 //some code here
})

require('cypress-failed-log')

Cypress.Keyboard.defaults({
  keystrokeDelay: 20,
})
tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "es5",
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "types": [
      "cypress",
      ***@***.***/cypress",
      ***@***.***/cy-grep",
      "cypress-real-events",
      "diff",
      "fs-extra",
      "adm-zip"
    ],
    "strict": true,
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowJs": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "isolatedModules": false,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "**/*.ts",
    "**/*.js"
  ],
}
example test file that will give error
describe('Test test', { tags: ***@***.***'] }, function () {
  context('Testing code', { tags: ***@***.***'] }, function () {
    it(`Does something good`, { tags: ***@***.***'] },function () {
      cy.contains('button', 'Start').click()
    })
  })
})

**Comment by nerrante** [comment]
OH!  Can do - will do that tonight!

**Comment by nerrante** [comment]
Kept it super simple - and reproducible at least for me locally! 
https://github.com/nerrante/cypresstest

**Comment by bahmutov** [comment]
This is because of the cypress-api-plugin - it has its own TestConfig object 

```js
// https://github.com/filiphric/cypress-plugin-api
import 'cypress-plugin-api'
```

<img width="1131" alt="Screenshot 2023-05-15 at 09 16 58" src="https://github.com/bahmutov/cy-grep/assets/2212006/d081ed88-49ab-44a6-8900-b3ab82bb1202">

<img width="964" alt="Screenshot 2023-05-15 at 09 17 13" src="https://github.com/bahmutov/cy-grep/assets/2212006/ab0bcfc9-4d97-45cb-9ee5-550c6fcca58d">

The solution is for `cypress-plugin-api` to make the `env` property optional

<img width="599" alt="Screenshot 2023-05-15 at 09 18 40" src="https://github.com/bahmutov/cy-grep/assets/2212006/779a5204-01c5-46a3-bf04-bd234a0fc4f7">

Opened an issue https://github.com/filiphric/cypress-plugin-api/issues/120

**Comment by nerrante** [comment]
Thanks Gleb - Filip already pushed the fix and all looks great using the new version of cypress-plugin-api.
